"""
Tools for calculations of Erlang B model (M/M/c/c) for queueing theory.

Model Erlang B opisuje system z:
- c channels (instances)
- ruchem A [Erlang]
- brakiem kolejki (blocked calls cleared)

Erlang B formula:
P_B = (A^c / c!) / Σ(k=0 to c) (A^k / k!)
"""

from typing import List, Tuple
import math


def calculate_traffic_per_demand(
    traffic: float = None,
    arrival_rate: float = None,
    service_rate: float = None,
    service_time: float = None
) -> float:
    """
    Calculates traffic intensity (traffic per demand) based on available parameters.
    
    Parameter priority:
    1. traffic (ready value in Erlangs)
    2. arrival_rate / service_rate (lambda / mu)
    3. arrival_rate * service_time (lambda * 1/mu)
    """
    if traffic is not None:
        return traffic
    
    if arrival_rate is not None:
        if service_rate is not None and service_rate > 0:
            return arrival_rate / service_rate
        if service_time is not None:
            return arrival_rate * service_time
            
    raise ValueError(
        "Cannot calculate traffic. Provide 'traffic' OR ('arrival_rate' AND 'service_rate'/'service_time')"
    )


def erlang_b(A: float, c: int) -> float:
    """
    Calculates the blocking probability for the Erlang B model (M/M/c/c).
    
    Uses a numerically stable recursive formula:
    B(A, c) = (A * B(A, c-1)) / (c + A * B(A, c-1))
    
    Args:
        A: load in Erlangs
        c: number of channels/servers (instances)
    
    Returns:
        Blocking probability P_B ∈ [0, 1]
    """
    if c == 0:
        return 1.0
    if A <= 0:
        return 0.0
    
    B = 1.0
    for i in range(1, c + 1):
        B = (A * B) / (i + A * B)
    return B


def find_min_instances(
    traffic_erlangs: float,
    target_blocking: float,
    max_search: int = None
) -> int:
    """
    Finds the minimum number of instances for a given load
    and the target blocking probability.
    """
    if traffic_erlangs <= 0:
        return 0
        
    if max_search is None:
        max_search = int(max(100, traffic_erlangs * 2.0 + 100))
    
    B = 1.0
    for c in range(1, max_search + 1):
        B = (traffic_erlangs * B) / (c + traffic_erlangs * B)
        if B <= target_blocking:
            return c
    
    return max_search


def generate_erlang_table(
    max_demands: int,
    traffic_per_demand: float = None,
    target_blocking: float = 0.01,
    arrival_rate: float = None,
    service_rate: float = None,
    service_time: float = None,
    srs_capacity: int = 1
) -> List[int]:
    """
    Generates a lookup table: number_of_demands -> minimum_number_of_instances.
    
    Index 0 means 0 demands (= 0 instances).
    Index n means n demands.
    
    Args:
        max_demands: maximum number of demands to serve
        traffic_per_demand: traffic generated by one demand [Erlang]
        target_blocking: docelowe P_B
        arrival_rate: lambda (if traffic_per_demand is not provided)
        service_rate: mu (opcjonalnie zamiast traffic)
        service_time: 1/mu (opcjonalnie zamiast traffic)
    
    Returns:
        List [min_instances for 0 demands, min_instances for 1 demand, ...]
    """
    traffic = calculate_traffic_per_demand(traffic_per_demand, arrival_rate, service_rate, service_time)
    
    table = [0]  # for 0 demands 0 instances are needed
    
    for n in range(1, max_demands + 1):
        A = n * traffic
        min_channels = find_min_instances(A, target_blocking)
        min_instances = math.ceil(min_channels / srs_capacity)
        table.append(min_instances)
    
    return table


def print_erlang_table(
    max_demands: int,
    traffic_per_demand: float = None,
    target_blocking: float = 0.01,
    arrival_rate: float = None,
    service_rate: float = None,
    service_time: float = None,
    srs_capacity: int = 1
) -> None:
    """Displays the Erlang table in a readable format."""
    traffic = calculate_traffic_per_demand(traffic_per_demand, arrival_rate, service_rate, service_time)
    
    print(f"\n{'='*75}")
    print(f" TABELA ERLANGA B")
    if arrival_rate:
        print(f" Parametry: λ={arrival_rate}, μ={service_rate if service_rate else '1/'+str(service_time)}")
    print(f" Traffic/demand = {traffic} Erl | Target P_B < {target_blocking*100}%")
    print(f"{'='*75}")
    print(f"{'Demands':>8} | {'Load [Erl]':>16} | {'Min. instances':>14} | {'Real P_B':>16}")
    print("-"*75)
    
    for n in range(0, max_demands + 1):
        A = n * traffic
        min_channels = find_min_instances(A, target_blocking) if n > 0 else 0
        c_instances = math.ceil(min_channels / srs_capacity) if n > 0 else 0
        actual_pb = erlang_b(A, c_instances * srs_capacity) if c_instances > 0 else 0.0
        status = "✅" if actual_pb <= target_blocking else "❌"
        print(f"{n:>8} | {A:>16.2f} | {c_instances:>14} | {actual_pb*100:>15.4f}% {status}")


def verify_erlang_solution(
    demands_per_cluster: List[int],
    instances: List[int],
    traffic_per_demand: float = None,
    target_blocking: float = 0.01,
    arrival_rate: float = None,
    service_rate: float = None,
    service_time: float = None,
    srs_capacity: int = 1
) -> List[Tuple[int, int, int, float, float, bool]]:
    """
    Verifies if the solution meets the Erlang model requirements.
    
    Args:
        demands_per_cluster: number of demands in each cluster
        instances: number of instances in each cluster
        traffic_per_demand: traffic per demand [Erl]
        target_blocking: docelowe P_B
    
    Returns:
        Lista krotek (cluster, demands, instances, traffic, actual_pb, ok)
    """
    traffic = calculate_traffic_per_demand(traffic_per_demand, arrival_rate, service_rate, service_time)

    results = []
    for c, (n_demands, n_instances) in enumerate(zip(demands_per_cluster, instances), 1):
        if n_demands > 0:
            A = n_demands * traffic
            total_channels = n_instances * srs_capacity
            actual_pb = erlang_b(A, total_channels)
            ok = actual_pb <= target_blocking
            results.append((c, n_demands, n_instances, A, actual_pb, ok))
    return results


# Usage example
if __name__ == "__main__":
    # Example parameters
    traffic_per_demand = 0.5  # Erlang per demand
    target_blocking = 0.01    # 1% blocking probability
    
    print_erlang_table(15, traffic_per_demand, target_blocking)
    
    # Generate table
    table = generate_erlang_table(20, traffic_per_demand, target_blocking)
    print(f"\n📊 Table for MiniZinc (first 15): {table[:16]}")
    
    # Test weryfikacji
    print("\n🔍 Test weryfikacji:")
    results = verify_erlang_solution(
        demands_per_cluster=[5, 3, 0, 2],
        instances=[4, 3, 0, 2],
        traffic_per_demand=0.5,
        target_blocking=0.01
    )
    for c, n, inst, A, pb, ok in results:
        status = "✅" if ok else "❌"
        print(f"   Cluster {c}: {n} demands, {inst} inst., A={A:.2f} Erl, P_B={pb*100:.4f}% {status}")
